### ISSUE TITLE
SSL Certificate issue

### ISSUE THREAD

**Issue by narayanapk** [gheeres/node-activedirectory#14]
Hi,

I am trying to authenticate user against AD. see below test code.

var ActiveDirectory = require('activedirectory');
var ad = new ActiveDirectory('ldaps://remoteserver:636', 'DC=myorg,DC=com');
var username="test_username";
var password="test_password";
ad.authenticate(username, password, function(err, auth) {
  if (err) {
    console.log('ERROR: '+JSON.stringify(err));
    return;
  }

  if (auth) {
    console.log('Authenticated!');
  }
  else {
    console.log('Authentication failed!');
  }
});

I ran into below issue executing test. Sounds like a certificate issue.
Can you please suggest how can i fix this?

D:\NODE_JS_CODE\ldapauth>node test.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: CERT_UNTRUSTED
    at SecurePair.<anonymous> (tls.js:1370:32)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:982:10)
    at CleartextStream.read [as _read](tls.js:469:13)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write](tls.js:366:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:583:24)

D:\NODE_JS_CODE\ldapauth>

**Comment by yosser22** [comment]
Hi Everybody,

I'm having the same Issue. The problem in my case is that  the certificate authority has been already imported and trusted. Testing it with an other application using the same certification and sending a request to the same ldap-server  shows that everything is working fine(The test-application is not a nodejs application). Only in the case of the nodejs application using this module, I'm getting the error CERT_UNTRUSTED. Can you please help me fix this error.  Thank you very much!

**Comment by improvisio** [comment]
I'm know that this is a BAD BAD advice but if you're looking for a quick fix until you resolve the issue properly, you can always choose to ignore untrusted certificates like this:
```
new ActiveDirectory({
   // ...
   tlsOptions: {
      'rejectUnauthorized': false
   }
});
```

**Comment by yosser22** [comment]
I don't know if I  did the right thing but I created a seperate issue here: https://github.com/gheeres/node-activedirectory/issues/94

**Comment by gheeres** [comment]
The SSL/TLS negotation is actually done by the underlying [ldapjs](http://ldapjs.org/) implementation.

As improvisio recommended, you can disable the untrusted certificate verification by sending in the ldapjs TLS options. Not a good idea since it does make you susceptible to man-in-the-middle attacks.

The solution to your problem is to ensure that the FULL certificate chain of trust is imported into your machine and available to ALL users. You need to make sure that the user that runs the nodejs process has that certificate chain available. Please refer back to my [blog post](http://blog.heeresonline.com/2014/05/nodejs-cert_untrusted-error/) for additional information and tips. Something is likely not setup or imported correctly.

If you're still having problems with your SSL/TLS negotiation, I'd recommend that you open or view the issues on the [ldapjs](https://github.com/mcavage/node-ldapjs/issues) repository.

**Comment by yosser22** [comment]
Hi I have another question:

can I expand the options of the active directory object and specify tls options??

Thank you

**Comment by yosser22** [comment]
so I fixed it by speicifying the .pem file in the tls option ca.

**Comment by cjh-Ella** [comment]
I have an error stating: ERROR: {"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"}
I read from https://auth0.com/docs/connector/troubleshooting#unable_to_verify_leaf_signature-error-message that i need to install the cert chain on server. But my server is Linux CentOS 7. I did as here advised: https://stackoverflow.com/questions/37043442/how-to-add-certificate-authority-in-centos7

But i still got the error. What should I do?

My code is like the following:

var ActiveDirectory = require("activedirectory");
const fs = require("fs");
var config = {
  url: "ldaps://xxx.com",
  baseDN: "DC=...,DC=com",
  tlsOptions: {
    ca: [fs.readFileSync("CA.crt")],
    rejectUnauthorized: true // Force Certificate Verification
  }
};
var ad = new ActiveDirectory(config);
var username = xxx;
var password = xxx;
ad.authenticate(username, password, function(err, auth) {
  if (err) {
    console.log("ERROR: " + JSON.stringify(err));
    return;
  }
  if (auth) {
    console.log("Authenticated!");
  } else {
    console.log("Authentication failed!");
  }
});

**Comment by cjh-Ella** [comment]
I set “rejectUnauthorized” to false

任先生 <notifications@github.com> schrieb am Fr. 31. Aug. 2018 um 08:52:

**Comment by emirefek** [comment]
> 

do you have chance to share how you fixed exactly? Because when I specified like this it's not working:

```
tlsOptions: {
        requestCert: true,
        rejectUnauthorized: true,
        ca: [fs.readFileSync("ldaps.pem")],
}
```

I still get 
`ERROR: {"code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE"}`
